# Generated by Django 4.1.4 on 2023-01-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_item_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('HOTEL', 'Hotel'), ('TOURIST_ATTRACTION', 'Tourist Attraction'), ('CONCERT', 'Concert'), ('AMUSEMENT_PARK', 'Amusement Park')], default='HOTEL', max_length=50),
            preserve_default=False,
        ),
    ]
