# Generated by Django 4.1.4 on 2023-01-01 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_item_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(choices=[('DXB', 'Dubai'), ('AD', 'Abu Dhabi'), ('RAK', 'Ras Al Khaimah'), ('SHJ', 'Sharjah')], max_length=100),
        ),
    ]
